spring:
  application:
    name: www
  datasource:
    url: jdbc:h2:file:./data/eu.wisniewska
    username: user
    password: password
    hikari:
      maximum-pool-size: 3
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console
  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: "/**"
      cache:
        cachecontrol:
          max-age: 365d

server:
  port: 8181
  tomcat:
    threads:
      max: 10
      min-spare: 2
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,application/json,application/xml,application/javascript,text/css,image/svg+xml
    min-response-size: 1024

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

app:
  admin:
    username: admin
    password: qwertyuiop
    role: ADMIN
    remember-me-key: secret-key
    remember-me-cookie-name: remember-me-cookie