spring:
  application:
    name: www
  datasource:
    url: jdbc:h2:file:./data/eu.wisniewska
    username: user
    password: password

server:
  port: 8181

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always